In [1]:
#generate some linear-looking data
import numpy as np

np.random.seed(0)
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1) #y = 4 + 3x + Gaussian noise

In [2]:
X_b = np.c_[np.ones((100,1)), X] #add 1 before each instance
theta = np.linalg.pinv(X_b).dot(y)
theta 
#result: y = 3.77x + 3.14, which is nearly y = 4 + 3x 

array([[4.22215108],
       [2.96846751]])

In [5]:
#test for input x = 2
X_test = [[0],[2]] #need [0] to perform matrix multiplication
X_test_new = np.c_[np.ones((2,1)), X_test] #purpose: để dimension đủ số dòng, số cột để nhân vào ma trận theta0, theta1 ở cell phía trên
y_predict = X_test_new.dot(theta)
y_predict #y(2) = 10.047

array([[ 3.77303795],
       [10.04746758]])

In [7]:
#Cách 2: dùng thư viện có sẵn -> nên dùng để test
from sklearn.linear_model import LinearRegression

model = LinearRegression() #khởi tạo biến model dùng constructor
model.fit(X,y)
model.intercept_, model.coef_ #theta0 & theta1

(array([4.22215108]), array([[2.96846751]]))

In [7]:
model.predict(X_test) #same result: y(2) = 10.047

array([[ 3.77303795],
       [10.04746758]])

In [8]:
#Cách 3: (batch) gradient descent 
alpha = 0.1 #learning rate
m = len(X) #100
theta = np.random.rand(2,1) #GD bắt đầu với theta ngẫu nhiên
iter = 0

while(1):
    iter += 1
    gradient = 2/m * X_b.T.dot(X_b.dot(theta) - y) #sử dụng X_b thay vì X để thực hiện nhân vector
    theta = theta - alpha*gradient
    if(np.linalg.norm(gradient) < 1e-4): #when the gradient becomes tiny
        break

theta, iter #correct: cần 258 vòng lặp để J(theta) đạt min

(array([[4.22193011],
        [2.96866358]]),
 258)